apiVersion: v1
kind: Service
metadata:
  name: client-service
  annotations:
    metallb.universe.tf/allow-shared-ip: sharing
spec:
  selector:
    app: frontend
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 30001

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-deployment
  labels:
    app: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: client
        image: localhost:32000/bookstore:frontend
        imagePullPolicy: Always
        ports:
          - containerPort: 3000