apiVersion: v1
kind: Service
metadata:
  name: server-service
  annotations:
    metallb.universe.tf/allow-shared-ip: sharing
spec:
  ports:
  - name: http
    protocol: TCP
    port: 8080
    targetPort: 8080
    nodePort: 30002
  selector:
    app: backend
  type: LoadBalancer

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-deployment
  labels:
    app: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: server
        image: localhost:32000/bookstore:backend
        imagePullPolicy: Always
        ports:
          - containerPort: 8080